[2024-12-23T05:46:08.182+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T05:46:08.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_location_data.upload_partitioned_data scheduled__2024-12-23T05:44:00+00:00 [queued]>
[2024-12-23T05:46:08.219+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_location_data.upload_partitioned_data scheduled__2024-12-23T05:44:00+00:00 [queued]>
[2024-12-23T05:46:08.219+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-12-23T05:46:08.234+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_partitioned_data> on 2024-12-23 05:44:00+00:00
[2024-12-23T05:46:08.246+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T05:46:08.247+0000] {standard_task_runner.py:63} INFO - Started process 4254 to run task
[2024-12-23T05:46:08.248+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_location_data', 'upload_partitioned_data', 'scheduled__2024-12-23T05:44:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_current_location.py', '--cfg-path', '/tmp/tmpn7yxgxyg']
[2024-12-23T05:46:08.249+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask upload_partitioned_data
[2024-12-23T05:46:08.304+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_location_data.upload_partitioned_data scheduled__2024-12-23T05:44:00+00:00 [running]> on host d64a5d849547
[2024-12-23T05:46:08.403+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_location_data' AIRFLOW_CTX_TASK_ID='upload_partitioned_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T05:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T05:44:00+00:00'
[2024-12-23T05:46:08.404+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T05:46:08.415+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T05:46:08.416+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_get_current_location.py", line 75, in put_airplane_data
    df.columns = [col.upper() for col in df.columns]
                                         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
[2024-12-23T05:46:08.427+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_location_data, task_id=upload_partitioned_data, run_id=scheduled__2024-12-23T05:44:00+00:00, execution_date=20241223T054400, start_date=20241223T054608, end_date=20241223T054608
[2024-12-23T05:46:08.440+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task upload_partitioned_data ('NoneType' object has no attribute 'columns'; 4254)
[2024-12-23T05:46:08.463+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-23T05:46:08.482+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T05:46:08.484+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
