[2024-12-23T05:45:10.143+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-23T05:45:10.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_location_data.upload_partitioned_data scheduled__2024-12-23T05:42:00+00:00 [queued]>
[2024-12-23T05:45:10.181+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_location_data.upload_partitioned_data scheduled__2024-12-23T05:42:00+00:00 [queued]>
[2024-12-23T05:45:10.181+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-12-23T05:45:10.198+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_partitioned_data> on 2024-12-23 05:42:00+00:00
[2024-12-23T05:45:10.210+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4231) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T05:45:10.214+0000] {standard_task_runner.py:63} INFO - Started process 4233 to run task
[2024-12-23T05:45:10.216+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_location_data', 'upload_partitioned_data', 'scheduled__2024-12-23T05:42:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_get_current_location.py', '--cfg-path', '/tmp/tmp74itcti7']
[2024-12-23T05:45:10.218+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask upload_partitioned_data
[2024-12-23T05:45:10.282+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_location_data.upload_partitioned_data scheduled__2024-12-23T05:42:00+00:00 [running]> on host d64a5d849547
[2024-12-23T05:45:10.386+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_location_data' AIRFLOW_CTX_TASK_ID='upload_partitioned_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T05:42:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T05:42:00+00:00'
[2024-12-23T05:45:10.390+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-23T05:45:10.403+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-23T05:45:10.403+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_get_current_location.py", line 75, in put_airplane_data
    df.columns = [col.upper() for col in df.columns]
                                         ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'columns'
[2024-12-23T05:45:10.417+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=upload_location_data, task_id=upload_partitioned_data, run_id=scheduled__2024-12-23T05:42:00+00:00, execution_date=20241223T054200, start_date=20241223T054510, end_date=20241223T054510
[2024-12-23T05:45:10.429+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task upload_partitioned_data ('NoneType' object has no attribute 'columns'; 4233)
[2024-12-23T05:45:10.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-23T05:45:10.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
